# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9919c587cffb376487eee5363e4541c36e5a8eab5363b066a4b1634d5108bf388a22139c6ce4253d26b657c43e436f6cdca159a8c5eaf6412400d091c290377

test:
  secret_key_base: 35390ff3a0cd1d4518c2364bae27ed5b3f35aa7f6b053a60ac7e0f2646a80e7fdda539ce226a0586ec59839fd112e396e6e92f20c38aa950c854ecc6463756e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
